### ISSUE TITLE
list of devices is empty

### ISSUE THREAD

**Issue by Inth** [JCxYIS/UnityBluetooth#1]
Hi Thank you so much for making this
after downloading V1 and checking if all permisions are ok 
the application does not see any BT devices around

any idea ?
Mat

**Comment by DenizYunus** [comment]
Same issue. All permissions are given. Works in my device, but doesn't works on 3 other friends :/

**Comment by JCxYIS** [comment]
Hi, I think the problem might be Android version issue. Android 12 made critical change to bt permission.
https://developer.android.com/develop/connectivity/bluetooth/bt-permissions
Have drafted a release, please test it out.

**Comment by DenizYunus** [comment]
Thanks! This worked well. Tested in 3 prior problematic phones, and all worked. Yey! 🥳
